package json

import (
	"testing"

	"github.com/chrsan/go/crdt"
	"github.com/stretchr/testify/assert"
)

func TestFromString(t *testing.T) {
	j, err := FromString(1, "")
	assert.NoError(t, err)
	assert.Nil(t, j)
	j, err = FromString(2, "123")
	assert.NoError(t, err)
	assert.NotNil(t, 2)
	v, err := j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, 123, v)
	j, err = FromString(1, "123.45")
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, 123.45, v)
	j, err = FromString(1, "true")
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, true, v)
	j, err = FromString(1, "null")
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.Nil(t, v)
	j, err = FromString(1, `"hello"`)
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, "hello", v)
	j, err = FromString(1, `{"foo": 123}`)
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, map[string]interface{}{"foo": int64(123)}, v)
	j, err = FromString(1, `{"foo": 123, "bar": true, "baz": [1.0, 2.0, 3.0]}`)
	assert.NoError(t, err)
	assert.NotNil(t, j)
	v, err = j.Value()
	assert.NoError(t, err)
	assert.EqualValues(t, map[string]interface{}{"foo": int64(123), "bar": true, "baz": []interface{}{1.0, 2.0, 3.0}}, v)
}

func TestObjectInsert(t *testing.T) {
	j, err := FromBuilder(1, func(b *Builder) {
		b.StartObject().EndObject()
	})
	assert.NoError(t, err)
	op1, err := j.InsertBuilder(func(b *Builder) { b.StartObject().FloatField("bar", 3.5).EndObject() }, "foo")
	assert.NoError(t, err)
	op2, err := j.Insert(Boolean(true), "foo", "baz")
	assert.NoError(t, err)
	assert.EqualValues(t, 3, j.summary.Counter(1))
	v, err := j.Value("foo", "bar")
	assert.NoError(t, err)
	assert.Equal(t, 3.5, v)
	v, err = j.Value("foo", "baz")
	assert.NoError(t, err)
	assert.Equal(t, true, v)
	assert.Nil(t, op1.Pointer)
	assert.IsType(t, InnerObjectOp{}, op1.Inner)
	assert.Equal(t, []UID{ObjectUID{Key: "foo", Dot: crdt.Dot{SiteID: 1, Counter: 2}}}, op2.Pointer)
}

func TestObjectInsertInvalidPointer(t *testing.T) {
	j, _ := FromString(1, "{}")
	_, err := j.InsertBuilder(func(b *Builder) { b.StartObject().FloatField("bar", 3.5).EndObject() }, "foo", "bar")
	assert.Error(t, err)
}

func TestObjectInsertReplacesValue(t *testing.T) {
	j, _ := FromString(1, "{}")
	_, err := j.Insert(Float(19.7), "foo")
	assert.NoError(t, err)
	op, err := j.Insert(Float(4.6), "foo")
	assert.NoError(t, err)
	assert.EqualValues(t, 3, j.summary.Counter(1))
	v, err := j.Value("foo")
	assert.NoError(t, err)
	assert.EqualValues(t, 4.6, v)
	assert.Nil(t, op.Pointer)
	assert.IsType(t, InnerObjectOp{}, op.Inner)
	inner := op.Inner.(InnerObjectOp)
	assert.Equal(t, "foo", inner.Key)
	assert.NotNil(t, inner.InsertedElement)
	assert.Equal(t, crdt.Dot{SiteID: 1, Counter: 3}, inner.InsertedElement.Dot)
	assert.EqualValues(t, 4.6, inner.InsertedElement.Value)
	assert.Equal(t, []crdt.Dot{crdt.Dot{SiteID: 1, Counter: 2}}, inner.RemovedDots)
}

func TestObjectInsertSameValue(t *testing.T) {
	j, _ := FromString(1, "{}")
	_, err := j.Insert(Float(19.7), "foo")
	assert.NoError(t, err)
	_, err = j.Insert(Float(19.7), "foo")
	assert.NoError(t, err)
	v, err := j.Value("foo")
	assert.NoError(t, err)
	assert.EqualValues(t, 19.7, v)
}

func TestObjectRemove(t *testing.T) {
	j, err := FromBuilder(1, func(b *Builder) {
		b.StartObject()
		b.StartArrayField("abc")
		b.AddFloat(1.5)
		b.AddBoolean(true)
		b.StartObject()
		b.BooleanField("def", false)
		b.EndObject()
		b.EndArray()
		b.EndObject()
	})
	assert.NoError(t, err)
	op, err := j.Remove("abc", 2, "def")
	assert.NoError(t, err)
	v, err := j.Value("abc", 2, "def")
	assert.NoError(t, err)
	assert.Nil(t, v)
	assert.Len(t, op.Pointer, 2)
	assert.Equal(t, ObjectUID{Key: "abc", Dot: crdt.Dot{SiteID: 1, Counter: 1}}, op.Pointer[0])
	assert.IsType(t, ArrayUID{}, op.Pointer[1])
	inner := op.Inner.(InnerObjectOp)
	assert.Equal(t, "def", inner.Key)
	assert.Nil(t, inner.InsertedElement)
	assert.Equal(t, []crdt.Dot{crdt.Dot{SiteID: 1, Counter: 1}}, inner.RemovedDots)
}
